[package]
name = "prototypes"
version = "0.1.0"
edition = "2021"

[dependencies]
rkyv = { version = "0.7.45", features = ["validation"] }
bytecheck = "0.6" # Required for rkyv validation

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "storage_bench"
harness = false
